# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec для Neuro KillAura Launcher

import os

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[os.getcwd()],
    binaries=[],
    datas=[
        ('configs', 'configs'),
        ('models', 'models'),
        ('launcher', 'launcher'),
        ('neuro_killaura', 'neuro_killaura'),
        ('visuals', 'visuals'),
        ('utils', 'utils'),
    ],
    hiddenimports=[
        'customtkinter',
        'customtkinter.windows',
        'customtkinter.windows.widgets',
        'customtkinter.windows.widgets.appearance_mode',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'PIL._tkinter_finder',
        'torch',
        'torch.nn',
        'torch.nn.functional',
        'numpy',
        'pygame',
        'pygame.font',
        'pygame.draw',
        'pygame.display',
        'pygame.time',
        'pynput',
        'pynput.keyboard',
        'pynput.mouse',
        'pynput._util',
        'psutil',
        'requests',
        'urllib.request',
        'ctypes',
        'json',
        'threading',
        'subprocess',
        'webbrowser',
        'minecraft_launcher_lib',
        'minecraft_launcher_lib.install',
        'minecraft_launcher_lib.command',
        'minecraft_launcher_lib.utils',
        'minecraft_launcher_lib.account',
        'minecraft_launcher_lib.microsoft_account',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'scipy',
        'pandas',
        'IPython',
        'jupyter',
        'notebook',
        'test',
        'unittest',
        'doctest',
        'pydoc',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='NeuroKillAura',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
    version_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='NeuroKillAura',
)
